// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvryt8u9VZOAgIGRBOSRH_h2zaL_Ai4I4',
    appId: '1:348401475785:web:3be5249301db526a1b6d18',
    messagingSenderId: '348401475785',
    projectId: 'instagram-tutorial-2bb53',
    authDomain: 'instagram-tutorial-2bb53.firebaseapp.com',
    storageBucket: 'instagram-tutorial-2bb53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbtYtJkJRF_6KewXbU8dA75oyPdUI4iTE',
    appId: '1:348401475785:android:380acf69b24b97bd1b6d18',
    messagingSenderId: '348401475785',
    projectId: 'instagram-tutorial-2bb53',
    storageBucket: 'instagram-tutorial-2bb53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi8T8EjkZEjRrIYSHUkzaFjci2oZe_0z4',
    appId: '1:348401475785:ios:1d250a7013cbd73a1b6d18',
    messagingSenderId: '348401475785',
    projectId: 'instagram-tutorial-2bb53',
    storageBucket: 'instagram-tutorial-2bb53.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi8T8EjkZEjRrIYSHUkzaFjci2oZe_0z4',
    appId: '1:348401475785:ios:a295c7440db9fca61b6d18',
    messagingSenderId: '348401475785',
    projectId: 'instagram-tutorial-2bb53',
    storageBucket: 'instagram-tutorial-2bb53.appspot.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
